#!/bin/sh

#variable i is the pdb file to be analyzed
#variable j is the rsa file generated by naccess of the complex
i=$1
j="${i%\.*}.rsa"

#split the chains of the complex. Chains should always be A and B.
pdb_selchain -A $1 > "${i%\.*}.A.pdb"
pdb_selchain -B $1 > "${i%\.*}.B.pdb"

# sort chains to avoid breaks if chains are not in order.
cat "${i%\.*}.A.pdb" "${i%\.*}.B.pdb" > "${i%\.*}.AB.pdb"

#run naccess for complex
naccess "${i%\.*}.AB.pdb" > out

#store naccess output to file
egrep "TOTAL" "${i%\.*}.rsa" > complex_buried.txt

#calculate percentages of polar, apolar and charged residues according to PROTORP definitions

egrep 'RES' $j  | cut -c 5-28 | awk '$5 >=  5' | awk '{print $3, $1, $2}' > Nsurf-res.txt
all=`cat Nsurf-res.txt | wc -l`
apol=`egrep "ALA|PHE|GLY|ILE|VAL|LEU|MET|PRO" Nsurf-res.txt | wc -l`
percent=`echo "$apol*100/$all" | bc -l`
apolar=`echo $percent | grep -o ".*\..."`
echo %NON-POLAR: "$apolar" > non-polar.txt

pol=`egrep "CYS|HIS|ASN|GLN|SER|THR|TRP|TYR" Nsurf-res.txt | wc -l`
percent=`echo "$pol*100/$all" | bc -l`
polar=`echo $percent | grep -o ".*\..."`
echo %POLAR: "$polar" > polar.txt

char=`egrep "ARG|LYS|ASP|GLU" Nsurf-res.txt | wc -l`
percent=`echo "$char*100/$all" | bc -l`
charged=`echo $percent | grep -o ".*\..."`
echo %CHARGED: "$charged" > charged.txt

mv "${i%\.*}.rsa" "${i%\.*}.AB.rsa"
mv "${i%\.*}.asa" "${i%\.*}.AB.asa"

naccess "${i%\.*}.A.pdb" > out
mv "${i%\.*}.rsa" "${i%\.*}.A.rsa"
mv "${i%\.*}.asa" "${i%\.*}.A.asa"
egrep "TOTAL" "${i%\.*}.A.rsa" > "${i%\.*}_A_buried.out"

naccess "${i%\.*}.B.pdb" > out
mv "${i%\.*}.rsa" "${i%\.*}.B.rsa"
mv "${i%\.*}.asa" "${i%\.*}.B.asa"
egrep "TOTAL" "${i%\.*}.B.rsa" > "${i%\.*}_B_buried.out"

#rm -rf out

cat "${i%\.*}.A.asa" "${i%\.*}.B.asa" > "${i%\.*}.AandB.asa"

cut -c 56-63 "${i%\.*}.AB.asa" > atoms-complex.txt
cut -c 56-63 "${i%\.*}.AandB.asa" > atoms-indivchains.txt
paste -d : atoms-complex.txt atoms-indivchains.txt > change_in_atoms.txt
g=`awk '{print ($3 - $1) " " }' change_in_atoms.txt | awk '$1 >=  1' | wc -l`
echo ATOMS-INT: "$g" > atoms_int.txt

cat non-polar.txt polar.txt charged.txt atoms_int.txt

rm -rf non-polar.txt polar.txt charged.txt atoms_int.txt
rm -rf atoms-complex.txt
rm -rf atoms-indivchains.txt
rm -rf change_in_atoms.txt
rm -rf entropy-contribution
rm -rf *.log
rm -r complex_buried.txt
rm -rf *.A.pdb
rm -rf *.B.pdb
rm -rf Nsurf-res.txt
rm -rf *_*_buried.out
rm -rf *.rsa *.asa
rm *.AB.pdb
#mv *.rsa *.asa *.[A-B].pdb *.out "${i%\.*}-pred"/output/.
#mv *.txt "${i%\.*}-pred"/.
exit
