name: publish to pypi

on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: builds and publishes to pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/prodigy-prot
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: build
        run: |
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
