name: publish to Test PyPI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry install

      - run: poetry run pytest

      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}

      - name: Publish package
        run: poetry publish --build -r testpypi
